spring.application.name=cinema-booking-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/cinemabooking_flyway
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-milliseconds=900000

stripe.secret-key=${STRIPE_SECRET_KEY}
stripe.currency=rsd
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}