CREATE TABLE app_users (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           first_name VARCHAR(100) NOT NULL,
                           last_name VARCHAR(100) NOT NULL,
                           email VARCHAR(255) NOT NULL,
                           password_hash VARCHAR(255) NOT NULL,
                           role VARCHAR(30) NOT NULL,
                           active BOOLEAN NOT NULL,
                           created_at TIMESTAMP NOT NULL,

                           CONSTRAINT uk_user_email UNIQUE (email),
                           CONSTRAINT chk_user_role
                               CHECK (role IN ('CUSTOMER', 'ADMIN'))
);

CREATE TABLE cinemas (
                         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(100) NOT NULL,
                         address VARCHAR(200) NOT NULL,
                         city VARCHAR(100) NOT NULL,
                         description VARCHAR(1000),
                         active BOOLEAN NOT NULL,

                         CONSTRAINT uk_cinema_name_city
                             UNIQUE (name, city)
);

CREATE TABLE movies (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        title VARCHAR(150) NOT NULL,
                        description VARCHAR(1000),
                        duration_minutes INTEGER NOT NULL,
                        release_date DATE NOT NULL,
                        age_rating VARCHAR(30) NOT NULL,
                        genre VARCHAR(30) NOT NULL,
                        language VARCHAR(50) NOT NULL,
                        director VARCHAR(100) NOT NULL,
                        poster_url VARCHAR(500),
                        trailer_url VARCHAR(500),
                        active BOOLEAN NOT NULL,

                        CONSTRAINT chk_movie_duration
                            CHECK (duration_minutes > 0),

                        CONSTRAINT chk_movie_age_rating
                            CHECK (
                                age_rating IN (
                                               'GENERAL',
                                               'SEVEN_PLUS',
                                               'TWELVE_PLUS',
                                               'SIXTEEN_PLUS',
                                               'EIGHTEEN_PLUS'
                                    )
                                ),

                        CONSTRAINT chk_movie_genre
                            CHECK (
                                genre IN (
                                          'ACTION',
                                          'COMEDY',
                                          'DRAMA',
                                          'HORROR',
                                          'THRILLER',
                                          'SCIENCE_FICTION',
                                          'FANTASY',
                                          'ANIMATION',
                                          'DOCUMENTARY'
                                    )
                                )
);

CREATE TABLE cinema_halls (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name VARCHAR(50) NOT NULL,
                              hall_type VARCHAR(30) NOT NULL,
                              cinema_id BIGINT NOT NULL,
                              active BOOLEAN NOT NULL,

                              CONSTRAINT uk_hall_name_cinema
                                  UNIQUE (name, cinema_id),

                              CONSTRAINT chk_hall_type
                                  CHECK (
                                      hall_type IN (
                                                    'STANDARD',
                                                    'THREE_D',
                                                    'IMAX',
                                                    'VIP'
                                          )
                                      ),

                              CONSTRAINT fk_hall_cinema
                                  FOREIGN KEY (cinema_id)
                                      REFERENCES cinemas (id)
);

CREATE TABLE hall_seats (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            row_label VARCHAR(10) NOT NULL,
                            seat_number INTEGER NOT NULL,
                            seat_type VARCHAR(30) NOT NULL,
                            active BOOLEAN NOT NULL,
                            hall_id BIGINT NOT NULL,

                            CONSTRAINT uk_seat_position_hall
                                UNIQUE (row_label, seat_number, hall_id),

                            CONSTRAINT chk_seat_number
                                CHECK (seat_number >= 1),

                            CONSTRAINT chk_seat_type
                                CHECK (
                                    seat_type IN (
                                                  'STANDARD',
                                                  'VIP',
                                                  'COUPLE',
                                                  'WHEELCHAIR_ACCESSIBLE'
                                        )
                                    ),

                            CONSTRAINT fk_seat_hall
                                FOREIGN KEY (hall_id)
                                    REFERENCES cinema_halls (id)
);

CREATE TABLE screenings (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            movie_id BIGINT NOT NULL,
                            hall_id BIGINT NOT NULL,
                            start_time TIMESTAMP NOT NULL,
                            end_time TIMESTAMP NOT NULL,
                            hall_available_at TIMESTAMP NOT NULL,
                            base_price NUMERIC(10, 2) NOT NULL,
                            status VARCHAR(30) NOT NULL,

                            CONSTRAINT chk_screening_price
                                CHECK (base_price > 0),

                            CONSTRAINT chk_screening_times
                                CHECK (
                                    end_time > start_time
                                        AND hall_available_at >= end_time
                                    ),

                            CONSTRAINT chk_screening_status
                                CHECK (
                                    status IN (
                                               'SCHEDULED',
                                               'CANCELLED',
                                               'COMPLETED'
                                        )
                                    ),

                            CONSTRAINT fk_screening_movie
                                FOREIGN KEY (movie_id)
                                    REFERENCES movies (id),

                            CONSTRAINT fk_screening_hall
                                FOREIGN KEY (hall_id)
                                    REFERENCES cinema_halls (id)
);

CREATE TABLE screening_seats (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 screening_id BIGINT NOT NULL,
                                 seat_id BIGINT NOT NULL,
                                 price NUMERIC(10, 2) NOT NULL,
                                 status VARCHAR(30) NOT NULL,
                                 reserved_until TIMESTAMP,
                                 version BIGINT,

                                 CONSTRAINT uk_screening_seat
                                     UNIQUE (screening_id, seat_id),

                                 CONSTRAINT chk_screening_seat_price
                                     CHECK (price > 0),

                                 CONSTRAINT chk_screening_seat_status
                                     CHECK (
                                         status IN (
                                                    'AVAILABLE',
                                                    'HELD',
                                                    'SOLD',
                                                    'BLOCKED'
                                             )
                                         ),

                                 CONSTRAINT fk_screening_seat_screening
                                     FOREIGN KEY (screening_id)
                                         REFERENCES screenings (id),

                                 CONSTRAINT fk_screening_seat_seat
                                     FOREIGN KEY (seat_id)
                                         REFERENCES hall_seats (id)
);

CREATE TABLE bookings (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          booking_reference VARCHAR(39) NOT NULL,
                          user_id BIGINT NOT NULL,
                          screening_id BIGINT NOT NULL,
                          status VARCHAR(30) NOT NULL,
                          created_at TIMESTAMP NOT NULL,
                          expires_at TIMESTAMP NOT NULL,
                          total_price NUMERIC(10, 2) NOT NULL,
                          version BIGINT,

                          CONSTRAINT uk_booking_reference
                              UNIQUE (booking_reference),

                          CONSTRAINT chk_booking_status
                              CHECK (
                                  status IN (
                                             'PENDING_PAYMENT',
                                             'CONFIRMED',
                                             'EXPIRED',
                                             'CANCELLED',
                                             'PAYMENT_FAILED'
                                      )
                                  ),

                          CONSTRAINT chk_booking_total_price
                              CHECK (total_price > 0),

                          CONSTRAINT fk_booking_user
                              FOREIGN KEY (user_id)
                                  REFERENCES app_users (id),

                          CONSTRAINT fk_booking_screening
                              FOREIGN KEY (screening_id)
                                  REFERENCES screenings (id)
);

CREATE TABLE booking_items (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               booking_id BIGINT NOT NULL,
                               screening_seat_id BIGINT NOT NULL,
                               price NUMERIC(10, 2) NOT NULL,

                               CONSTRAINT uk_booking_screening_seat
                                   UNIQUE (booking_id, screening_seat_id),

                               CONSTRAINT chk_booking_item_price
                                   CHECK (price > 0),

                               CONSTRAINT fk_booking_item_booking
                                   FOREIGN KEY (booking_id)
                                       REFERENCES bookings (id),

                               CONSTRAINT fk_booking_item_screening_seat
                                   FOREIGN KEY (screening_seat_id)
                                       REFERENCES screening_seats (id)
);

CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          booking_id BIGINT NOT NULL,
                          provider_payment_id VARCHAR(255),
                          provider VARCHAR(30) NOT NULL,
                          status VARCHAR(30) NOT NULL,
                          amount NUMERIC(12, 2) NOT NULL,
                          currency VARCHAR(3) NOT NULL,
                          created_at TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP NOT NULL,
                          version BIGINT,

                          CONSTRAINT uk_payment_booking
                              UNIQUE (booking_id),

                          CONSTRAINT uk_provider_payment_id
                              UNIQUE (provider_payment_id),

                          CONSTRAINT chk_payment_provider
                              CHECK (provider IN ('STRIPE')),

                          CONSTRAINT chk_payment_status
                              CHECK (
                                  status IN (
                                             'PENDING',
                                             'SUCCEEDED',
                                             'FAILED',
                                             'CANCELLED'
                                      )
                                  ),

                          CONSTRAINT chk_payment_amount
                              CHECK (amount > 0),

                          CONSTRAINT fk_payment_booking
                              FOREIGN KEY (booking_id)
                                  REFERENCES bookings (id)
);

CREATE INDEX idx_hall_seats_hall_id
    ON hall_seats (hall_id);

CREATE INDEX idx_screenings_movie_id
    ON screenings (movie_id);

CREATE INDEX idx_screenings_hall_id
    ON screenings (hall_id);

CREATE INDEX idx_screenings_status_start_time
    ON screenings (status, start_time);

CREATE INDEX idx_screening_seats_screening_status
    ON screening_seats (screening_id, status);

CREATE INDEX idx_screening_seats_reserved_until
    ON screening_seats (reserved_until);

CREATE INDEX idx_bookings_user_id
    ON bookings (user_id);

CREATE INDEX idx_bookings_screening_id
    ON bookings (screening_id);

CREATE INDEX idx_bookings_status_expires_at
    ON bookings (status, expires_at);

CREATE INDEX idx_booking_items_screening_seat_id
    ON booking_items (screening_seat_id);